import Vue from 'vue'
import Router from 'vue-router'
import Resource from 'vue-resource'
import IndexPage from '@/components/Index'
import LiveMap from '@/components/LiveMap'
import InfoCtrl from '@/components/InfoCtrl'
import PersonCtrl from '@/components/PersonCtrl'
import CarList from '@/components/CarList'
import CarArrival from '@/components/CarArrival'
import Weather from '@/components/Weather'
import Message from '@/components/Message'
import Breakdown from '@/components/Breakdown'
import ToPerson from '@/components/ToPerson'
import Developing from '@/components/Developing'
import Login from '@/components/Login'

Vue.use(Router)
Vue.use(Resource)

export default new Router({
  routes: [
    {
      path: '/',
      component: IndexPage,
      children:[
        {
          path:'/',
          component:LiveMap,
          children:[
            {
              path:'/',
              component:CarArrival
            },
            {
              path:'/cararrival',
              component:CarArrival
            },
            {
              path:'/weather',
              component:Developing
            },
            {
              path:'/message',
              component:Developing
            },
            {
              path:'/breakdown',
              component:Developing
            },
            {
              path:'/toperson',
              component:Developing
            },
          ]
        },
        {
          path:'/livemap',
          component:LiveMap,
          children:[
            {
              path:'/',
              component:CarArrival
            },
            {
              path:'/cararrival',
              component:CarArrival
            },
            {
              path:'/weather',
              component:Developing
            },
            {
              path:'/message',
              component:Developing
            },
            {
              path:'/breakdown',
              component:Developing
            },
            {
              path:'/toperson',
              component:Developing
            },
          ]
        },
        {
          path:'/infoctrl',
          component:InfoCtrl
        },
        {
          path:'/personctrl',
          component:PersonCtrl
        },
        {
          path:'/carlist',
          component:CarList
        }
      ]
    },
    {
      path: '/index',
      component: IndexPage,
      children:[
        {
          path:'/',
          component:LiveMap,
          children:[
            {
              path:'/',
              component:CarArrival
            },
            {
              path:'/cararrival',
              component:CarArrival
            },
            {
              path:'/weather',
              component:Developing
            },
            {
              path:'/message',
              component:Developing
            },
            {
              path:'/breakdown',
              component:Developing
            },
            {
              path:'/toperson',
              component:Developing
            },
          ]
        },
        {
          path:'/livemap',
          component:LiveMap,
          children:[
            {
              path:'/',
              component:CarArrival
            },
            {
              path:'/cararrival',
              component:CarArrival
            },
            {
              path:'/weather',
              component:Developing
            },
            {
              path:'/message',
              component:Developing
            },
            {
              path:'/breakdown',
              component:Developing
            },
            {
              path:'/toperson',
              component:Developing
            },
          ]
        },
        {
          path:'/infoctrl',
          component:InfoCtrl
        },
        {
          path:'/personctrl',
          component:PersonCtrl
        },
        {
          path:'/carlist',
          component:CarList
        }
      ]
    },
    {
      path:'/login',
      component:Login
    }
  ]
  /*routes: [
    {
      path: '/',
      component: IndexPage,
      children:[
        {
          path:'/',
          component:LiveMap,
          children:[
            {
              path:'/',
              component:CarArrival
            },
            {
              path:'/cararrival',
              component:CarArrival
            },
            {
              path:'/weather',
              component:Weather
            },
            {
              path:'/message',
              component:Message
            },
            {
              path:'/breakdown',
              component:Breakdown
            },
            {
              path:'/toperson',
              component:ToPerson
            },
          ]
        },
        {
          path:'/livemap',
          component:LiveMap,
          children:[
            {
              path:'/',
              component:CarArrival
            },
            {
              path:'/cararrival',
              component:CarArrival
            },
            {
              path:'/weather',
              component:Weather
            },
            {
              path:'/message',
              component:Message
            },
            {
              path:'/breakdown',
              component:Breakdown
            },
            {
              path:'/toperson',
              component:ToPerson
            },
          ]
        },
        {
          path:'/infoctrl',
          component:InfoCtrl
        },
        {
          path:'/personctrl',
          component:PersonCtrl
        }
      ]
    },
    {
      path: '/index',
      component: IndexPage,
      children:[
        {
          path:'/',
          component:LiveMap,
          children:[
            {
              path:'/',
              component:CarArrival
            },
            {
              path:'/cararrival',
              component:CarArrival
            },
            {
              path:'/weather',
              component:Weather
            },
            {
              path:'/message',
              component:Message
            },
            {
              path:'/breakdown',
              component:Breakdown
            },
            {
              path:'/toperson',
              component:ToPerson
            },
          ]
        },
        {
          path:'/livemap',
          component:LiveMap,
          children:[
            {
              path:'/',
              component:CarArrival
            },
            {
              path:'/cararrival',
              component:CarArrival
            },
            {
              path:'/weather',
              component:Weather
            },
            {
              path:'/message',
              component:Message
            },
            {
              path:'/breakdown',
              component:Breakdown
            },
            {
              path:'/toperson',
              component:ToPerson
            },
          ]
        },
        {
          path:'/infoctrl',
          component:InfoCtrl
        },
        {
          path:'/personctrl',
          component:PersonCtrl
        }
      ]
    },
  ]*/
})
